### ISSUE TITLE
table of output variables

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates-docs#1]
we should make a table of all possible output variables, with units, dimensions, and descriptions, as an appendix to this tech note.

**Comment by serbinsh** [comment]
I second this!

**Comment by rgknox** [comment]
for this... I wonder if we can leverage in-code text strings, something doxygen-like to help us keep this current.
I'm imaging that if we don't it will become out of date quickly.

**Comment by ckoven** [comment]
or write some sort of code to parse the netcdf metadata of a history file?

**Comment by ckoven** [comment]
and ditto for #4 -- maybe we can leverage one of the existing python tools to do that?

**Comment by glemieux** [comment]
Getting auto documentation going for in-code comments is something that I'd like to work on implementing.

**Comment by adrifoster** [comment]
@ckoven, @glemieux, and @rgknox just saw this. Perhaps I can do something with the updates I just made?

**Comment by glemieux** [comment]
> @ckoven, @glemieux, and @rgknox just saw this. Perhaps I can do something with the updates I just made?

That sounds like a good idea.  We should put this on the fates software agenda for discussion.

**Comment by glemieux** [comment]
Closing per https://github.com/NGEET/fates-users-guide/issues/45.
