### ISSUE TITLE
switch to math jax?

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates-docs#31]
I vaguely recall that math jax might provide crisper equations, this option is available in our documentation build system.  Perhaps we should change to it.

**Comment by rgknox** [comment]
I just happened to be looking at this biogeosciences ref by Martinez-Cano et al., and I noticed they had an optional MathJax method of rendering the equations:

https://bg.copernicus.org/articles/16/847/2019/

I thought the mathjax really looked much nicer, it would be nice to give it a try here

**Comment by wwieder** [comment]
@olyson, maybe we can try something similar with the CLM documentation?

**Comment by olyson** [comment]
No idea how to do this right now, but maybe we can bring it up at a software meeting.

**Comment by glemieux** [comment]
We will likely need a requirements.txt file to specify the mathjax package to use, which fates-docs currently does not have.  See [fates-users-guide](https://github.com/NGEET/fates-users-guide/blob/main/docs/requirements.txt) for example.

**Comment by glemieux** [comment]
Note that @adamhb tested out mathjax locally on his setup with success per https://github.com/NGEET/fates-docs/pull/57#discussion_r1329420154.  His PR #57 has a commit with the config update including mathjax that is commented out.  We should try and enable this in a future PR.

**Comment by glemieux** [comment]
Closing per #66
