### ISSUE TITLE
Need documentation of respiration acclimation model

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates-docs#45]
corresponding to https://github.com/NGEET/fates/pull/931

**Comment by ckoven** [comment]
should go in section https://fates-users-guide.readthedocs.io/projects/tech-doc/en/stable/fates_tech_note.html#plant-respiration

**Comment by ckoven** [comment]
cc @JessicaNeedham to note the possible negative values issue https://github.com/NGEET/fates/issues/1085 in the documentation of this

**Comment by JessicaNeedham** [comment]
Addressed by PR #58 .
