### ISSUE TITLE
Setup standard templates for bug reports/feature requests

### ISSUE THREAD

**Issue by serbinsh** [NGEET/fates-docs#6]
Probably not a high priority but we may want to setup standard templates for bug reporting and/or requesting new FATES features.  For example (and sorry I am always using this as an example) but with PEcAn we have two options upon submitting a new issue:

![screen shot 2018-09-20 at 4 38 08 pm](https://user-images.githubusercontent.com/3067369/45845722-e2073c80-bcf3-11e8-9d17-6d0de1203f6a.png)

Then say in bug reporting we have:

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Machine (please complete the following information):**
 - Server [e.g. BU, NCSA, VM, etc.]
 - OS: [e.g.Linux]
 - Browser(if applicable) [e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

```

Just showing that as an example...This way we could provide a general guideline for info we would like to see when reporting the bug, etc...Just a thought.

**Comment by ckoven** [comment]
@serbinsh good idea but this should go into the FATES repo, not this (FATES-docs) repo.  Could you open it there?

**Comment by serbinsh** [comment]
Yeah I just realized I was in the wrong repo! SOrry.. moving it now
